[package]
name = "gcoma"
description = "Geri's Connection Manager"
repository = "https://github.com/weyh/gcoma"
version = "1.0.2"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
strum = "0.23"
strum_macros = "0.23"
ansi_term = "0.12"
clap = { version = "3.0.7", features = ["derive"] }
